version: '3'

services:
  discovery-server:
    container_name: discovery-server
    image: discovery-server
    build:
      context: discover-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - "8761"
    restart: always
  product-service-db:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./data/mongo/db:/data/mongo
  order-service-db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
      - ./database/order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command: -p 5432
    restart: always
  inventory-service-db:
    container_name: mysql
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-service
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./database/inventory-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always