-- liquibase formatted sql

-- changeset swann:1697890274973-1
CREATE TABLE customer_order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number VARCHAR(255),
    CONSTRAINT pk_customer_order PRIMARY KEY (id)
);

-- changeset swann:1697890274973-2
CREATE TABLE customer_order_line_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku_code VARCHAR(255),
    price    DECIMAL,
    quantity INTEGER,
    CONSTRAINT pk_customer_order_line_items PRIMARY KEY (id)
);

-- changeset swann:1697890274973-3
CREATE TABLE customer_order_order_line_items
(
    order_id            BIGINT NOT NULL,
    order_line_items_id BIGINT NOT NULL
);

-- changeset swann:1697890274973-4
ALTER TABLE customer_order_order_line_items
    ADD CONSTRAINT uc_customer_order_order_line_items_orderlineitems UNIQUE (order_line_items_id);

-- changeset swann:1697890274973-5
ALTER TABLE customer_order_order_line_items
    ADD CONSTRAINT fk_cusordordlinite_on_order FOREIGN KEY (order_id) REFERENCES customer_order (id);

-- changeset swann:1697890274973-6
ALTER TABLE customer_order_order_line_items
    ADD CONSTRAINT fk_cusordordlinite_on_order_line_items FOREIGN KEY (order_line_items_id) REFERENCES customer_order_line_items (id);

