spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://order-service-db:5432/order-service
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
  config:
    import: "optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/"
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-timeout: 5s
      config:
        enabled: true
server:
  port: 8182

logging:
  level:
    root: INFO

networks:
  swann_network:
    driver: bridge